### PR TITLE
fix lib/soef crashes

### PR DESCRIPTION
**Pull request by Garfonso**
by adding local lib/soef.

Also updates some meta information to point to right git and so on.

### CODE REVIEW

**Comment by Apollon77** [comment]
Nimm bitte nch nodejs 8 aus den tests bei travis/appveyor raus

**Comment by Apollon77** [comment]
Und bitte noch das Repo (und damit auch alles) wieder zurück auf ohne community ... nur die npm Pakete haben wir

**Comment by foxriver76** [comment]
I've updated testing and adjusted repo name + opened PR https://github.com/ioBroker/ioBroker.repositories/pull/729. Please fix all occurences 
```diff
- iobroker.yamaha.community
+ iobroker.yamaha
```

**Comment by foxriver76** [comment]
And if you are interested in some more fixes, check out the checklist https://github.com/ioBroker/ioBroker.repositories/pull/729#issuecomment-618869001

**Comment by Garfonso** [comment]
I'll see if I find time for the other issues.

**Comment by foxriver76** [comment]
Thank you.

**Pull request merged**
